### ISSUE TITLE
incorrect `flag: light-uninstall` in generated opam files

### ISSUE THREAD

**Issue by mseri** [AltGr/opam-package-upgrade#3]
If `opam-package-upgrade` is installed, it forces `opam-state` to be downgraded to `2.0.0~beta3.2`, the net outcome is that when the packages are upgrded manually (https://gist.github.com/mseri/b0d28a9c56303ac17580da9b494a68ce) or by other tools, such as `dune-release`, the generated file will contain the unnecessary `flag: light-uninstall`.

**Comment by mseri** [comment]
I am raising the issue because even if that this seems to be fixed since July, for some reasons, in around a third of my recent installations of the tools (all made on fresh environments in the last couple of months) the solver decided that downgrading `ocaml-client` the library was right thing to do

**Comment by XVilka** [comment]
Is this still a problem?

**Comment by mseri** [comment]
I don't know, I have not used the tool recently and all my project are now ported to dune so I cannot really test it thorougly. However, I have not noticed this problem appearing in the opam-repository for a while so I think it is safe to assume that it is no longer an issue. I will re-open it in case it happens again.
