### ISSUE TITLE
Release the new version

### ISSUE THREAD

**Issue by XVilka** [AltGr/opam-package-upgrade#5]
It is required for https://github.com/ocaml/ocaml-ci-scripts/pull/258

**Comment by hannesm** [comment]
indeed, it would be nice to get a new release of this great package. thanks! :)

**Comment by AltGr** [comment]
Sorry for the lag! https://github.com/ocaml/opam-repository/pull/16059

**Comment by XVilka** [comment]
Thank you, fixed!
